
int? userId;
const mainUrl = "https://habitseveryday.com/public/";
const loginUrl = "api/login";
const editProfiles = "api/updateProfile";
const registerUrl = "api/register";
const profileUrl = "api/getProfile";
const bannerUrl = "api/banner";
const taskUserUrl = "api/task-assigned-users";
const taskComment= "api/task-comments-post";
const taskCommentGet = "api/task-comments";
const taskUserNotifyUrl = "api/task-notified-users";
const taskMyUrl = "api/task_get_by_user";
const taskByUrl = "api/task-assigned-users-all";
const taskUpdateUrl = "api/task-status-update";
const accountUrl = "api/accounts-save";
const accountCategoryUrl = "api/cash-category";
const incomeExpenses = "api/income_expenses";
const addCategoryUrl = "api/cash-category-post";
const cashInGetUrl = "api/accounts-get";
