import 'package:flutter/material.dart';

const APPBACKGROUNDCOLOR = Color(0xFF0d003f);
const BUTTONTEXTCOLOR = Color(0xFFFFFFFFFF);
const BLACKCOLOR = Color(0xff000000);
const INCOMECARDCOLOR = Color(0xFF3eb290);
const EXPENSESCARDCOLOR = Color(0XFFFF597B);
const INCOMECARDTEXTCOLOR = Color(0xFFFFFFFFF);
const EXPENSECARDTEXTCOLOR = Color(0XFFFFFFFF);
const INCOMEEXPENSESCARDTEXTCOLOR = Color(0XFFFFFFFFF);
const INCOMEAMOUNTTEXTCOLOR = Color(0XFF4CAF50);
const EXPENSESAMOUNTTEXTCOLOR = Color(0XFFF44336);
const ACCOUNTTRANCATIONCARDCOLOR = Color(0XFFBCEAD5);
const ASSIGNEDALLTASKCARDCOLOR = Color(0XFF570A57);
// const EXPENSESCARDCOLOR = Color(0XFFFFF5E1);
const DEBITCARDCOLOR = Color(0XFFC9CCD5);
const TASKPAGEVIEWTEXTCOLOR = Color(0xff0b4b5b);
const TASKPAGEVIEWBUTTONCOLOR = Color(0xffffae46);

String REGISTER_IMG = 'assets/images/register.png';
String LOGIN_IMG = "assets/images/login.png";
String ASSIGNTOYOU = "assets/icons/Assigntoyou.png";
String ASSIGNTOME = "assets/icons/assignedtome.png";
String NOTIFY = "assets/icons/Notificationicon.png";
String UNLOCKCREDITICON = "assets/icons/Unlockpowercrediticon.png";
String BARCHARTICON = "assets/icons/barcharticon.png";
String CREDITICON = "assets/icons/Creditlogo.png";
String ATMICON = "assets/icons/Atm.logo.png";
String NETBANKINGICON = "assets/icons/Netbanking.logo.png";
String UPIFOUNDSICON = "assets/icons/upi.logo.png";
String MORNINGICON = "assets/icons/sunicon.png";
String AFTERNOONICON = "assets/icons/Afernoonicon.png";
String EVENINGICON = "assets/icons/eveningicon.png";
String INCOMEARROWICON = "assets/icons/Incomearrow.icon.png";
String EXPENCESARROWICON = "assets/icons/Expansesarrow.logo.png";
String PROJECTICON = "assets/icons/project.png";
String DATEICON = "assets/icons/dateicon.png";
String COMMENTSICON = 'assets/icons/commentsicon.png';
String TEAMICON = 'assets/icons/team.png';
const String MAIL_ICON = 'assets/icons/mailIcon.png';
 